name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.3, 3.4, 4.0]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: '2.5.6'
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
  coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0'
        bundler: '2.5.6'
        bundler-cache: true
    - name: Run tests for coverage
      run: bundle exec rake
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0'
        bundler: '2.5.6'
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop --force-exclusion
